# Generated by Django 5.0.3 on 2024-03-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tbhost_tbitens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbitens',
            old_name='hostusrid',
            new_name='itemusrid',
        ),
    ]
