# Generated by Django 5.0.3 on 2024-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_hostusrid_tbitens_itemusrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbitens',
            name='itemdscreport',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
