# Generated by Django 5.0.3 on 2024-03-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_tbitens_itemdscreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiurl', models.CharField(max_length=100)),
                ('apiusr', models.CharField(max_length=50)),
                ('apipass', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbapi',
            },
        ),
    ]
