# Generated by Django 5.0.3 on 2024-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_tbapi_apiusrid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbapi',
            name='apipass',
            field=models.CharField(max_length=100),
        ),
    ]
