# Generated by Django 5.0.3 on 2024-03-26 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_tbhostgroup_gpzbxid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbitens',
            name='itemzbxid',
        ),
        migrations.CreateModel(
            name='TBMiddleHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdhhostgpid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tbhostgroup')),
                ('mdhhostid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tbhost')),
                ('mdhhostusrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbmiddlehost',
            },
        ),
        migrations.CreateModel(
            name='TBMiddleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdiitemid', models.IntegerField()),
                ('mdiitemname', models.CharField(max_length=50)),
                ('mdihostid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tbhost')),
                ('mdiusrid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbmiddleitem',
            },
        ),
    ]
