# Generated by Django 5.0.3 on 2024-03-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_tbitens_itemzbxid_tbmiddlehost_tbmiddleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbhost',
            name='hostgpid',
        ),
    ]
