# Generated by Django 5.0.3 on 2024-03-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_tbhostgroup_gpzbxid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbitens',
            name='itemdscreport',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
