# Generated by Django 5.0.3 on 2024-03-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_tbitens_itemdscreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbitens',
            name='itemname',
            field=models.CharField(max_length=400),
        ),
    ]
