# Generated by Django 5.0.3 on 2024-03-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_tblayout_tbmiddlelayout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblayout',
            old_name='itemusrid',
            new_name='layoutusrid',
        ),
        migrations.AlterField(
            model_name='tblayout',
            name='layoutlogo',
            field=models.FileField(upload_to='logo'),
        ),
    ]
